[mgr]
keymap = [
	{ on = "h", run = "find_arrow",              desc = "Next found" },
	{ on = "H", run = "find_arrow --previous",   desc = "Previous found" },
	{ on = "n", run = "leave", desc = "Back to the parent directory" },
	{ on = "N", run = "back",    desc = "Back to previous directory" },

	{ on = "e", run = "arrow next", desc = "Next task" },
	{ on = "E", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	{ on = "k", run = "insert",                          desc = "Enter insert mode" },
	{ on = "K", run = [ "move first-char", "insert" ],   desc = "Move to the BOL, and enter insert mode" },
	{ on = "i", run = "arrow prev", desc = "Previous file" },
	{ on = "I", run = "seek -5", desc = "Seek up 5 units in the preview" },

	{ on = "l",         run = "open",                        desc = "Open selected files" },
	{ on = "L",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "o", run = "enter", desc = "Enter the child directory" },
	{ on = "O", run = "forward", desc = "Forward to next directory" }

]
